/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "我是一只鱼",
  "description": "我是一只快乐的鱼的网站，欢迎前来参观",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          },
          {
            "title": "测试标题",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-03133c90",
      "path": "/"
    },
    {
      "title": "page-aaaaaa 内部的",
      "frontmatter": {
        "sidebar": "auto",
        "title": "page-aaaaaa 内部的"
      },
      "regularPath": "/page-a.html",
      "relativePath": "page-a.md",
      "key": "v-38e7246e",
      "path": "/page-a.html",
      "headers": [
        {
          "level": 2,
          "title": "1. 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 3,
          "title": "1. 三级标题",
          "slug": "_1-三级标题"
        },
        {
          "level": 3,
          "title": "2. 三级标题",
          "slug": "_2-三级标题"
        },
        {
          "level": 2,
          "title": "2. 二级标题",
          "slug": "_2-二级标题"
        }
      ]
    },
    {
      "title": "我是about页面我是四级标题",
      "frontmatter": {
        "sidebarDepth": 2,
        "navbar": false
      },
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-77c7b87a",
      "path": "/about.html"
    },
    {
      "title": "我是page-b页面",
      "frontmatter": {},
      "regularPath": "/page-b.html",
      "relativePath": "page-b.md",
      "key": "v-7259b772",
      "path": "/page-b.html"
    }
  ],
  "themeConfig": {
    "logo": "/images/logo.png",
    "navbar": true,
    "nav": [
      {
        "text": "Home",
        "link": "/",
        "target": "_self",
        "rel": ""
      },
      {
        "text": "About",
        "link": "/about"
      },
      {
        "text": "分享链接",
        "link": "https://google.com"
      },
      {
        "text": "Language",
        "items": [
          {
            "text": "Home",
            "link": "/"
          },
          {
            "text": "About",
            "items": [
              {
                "text": "爱睡觉",
                "link": "/about"
              },
              {
                "text": "音乐迷",
                "link": "/about2"
              }
            ]
          }
        ]
      }
    ],
    "sidebar": {
      "/": [
        "",
        "about",
        "page-a",
        [
          "page-a",
          "pagea - 对象"
        ],
        [
          "page-b",
          "pageb - 对象"
        ]
      ]
    }
  }
}